// Code generated by protoc-gen-go.
// source: action.proto
// DO NOT EDIT!

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	action.proto
	article.proto
	request.proto

It has these top-level messages:
	LikeAction
	Article
	Request
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LikeAction struct {
	Id          int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Target      int64 `protobuf:"varint,2,opt,name=target" json:"target,omitempty"`
	UserId      int64 `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	IsFriend    bool  `protobuf:"varint,4,opt,name=is_friend,json=isFriend" json:"is_friend,omitempty"`
	CreatedUtc  int64 `protobuf:"varint,14,opt,name=created_utc,json=createdUtc" json:"created_utc,omitempty"`
	ModifiedUtc int64 `protobuf:"varint,15,opt,name=modified_utc,json=modifiedUtc" json:"modified_utc,omitempty"`
	Deleted     bool  `protobuf:"varint,16,opt,name=deleted" json:"deleted,omitempty"`
	DeletedUtc  int64 `protobuf:"varint,17,opt,name=deleted_utc,json=deletedUtc" json:"deleted_utc,omitempty"`
}

func (m *LikeAction) Reset()                    { *m = LikeAction{} }
func (m *LikeAction) String() string            { return proto.CompactTextString(m) }
func (*LikeAction) ProtoMessage()               {}
func (*LikeAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LikeAction) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LikeAction) GetTarget() int64 {
	if m != nil {
		return m.Target
	}
	return 0
}

func (m *LikeAction) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LikeAction) GetIsFriend() bool {
	if m != nil {
		return m.IsFriend
	}
	return false
}

func (m *LikeAction) GetCreatedUtc() int64 {
	if m != nil {
		return m.CreatedUtc
	}
	return 0
}

func (m *LikeAction) GetModifiedUtc() int64 {
	if m != nil {
		return m.ModifiedUtc
	}
	return 0
}

func (m *LikeAction) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *LikeAction) GetDeletedUtc() int64 {
	if m != nil {
		return m.DeletedUtc
	}
	return 0
}

func init() {
	proto.RegisterType((*LikeAction)(nil), "models.LikeAction")
}

func init() { proto.RegisterFile("action.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x34, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0x57, 0xba, 0xeb, 0xec, 0xb2, 0x6a, 0x0e, 0x1a, 0xf0, 0xe0, 0xea, 0x69, 0x4f,
	0x5e, 0x7c, 0x02, 0x2f, 0x82, 0xe0, 0xa9, 0xd0, 0x73, 0xa9, 0x99, 0xa9, 0x0c, 0xb6, 0x8d, 0x24,
	0xd3, 0x87, 0xf6, 0x2d, 0x96, 0x4e, 0xd3, 0x5b, 0xbe, 0x6f, 0xfe, 0xff, 0x87, 0xc0, 0xa1, 0xf5,
	0xc2, 0x61, 0x7c, 0xfd, 0x8b, 0x41, 0x82, 0x2d, 0x87, 0x80, 0xd4, 0xa7, 0x97, 0x7f, 0x03, 0xf0,
	0xc5, 0xbf, 0xf4, 0xae, 0x47, 0x7b, 0x84, 0x82, 0xd1, 0x99, 0x93, 0x39, 0x6f, 0xaa, 0x82, 0xd1,
	0xde, 0x43, 0x29, 0x6d, 0xfc, 0x21, 0x71, 0x85, 0xba, 0x4c, 0xf6, 0x01, 0xb6, 0x53, 0xa2, 0xd8,
	0x30, 0xba, 0xcd, 0x72, 0x98, 0xf1, 0x13, 0xed, 0x23, 0x5c, 0x73, 0x6a, 0xba, 0xc8, 0x34, 0xa2,
	0xbb, 0x3a, 0x99, 0xf3, 0xae, 0xda, 0x71, 0xfa, 0x50, 0xb6, 0x4f, 0xb0, 0xf7, 0x91, 0x5a, 0x21,
	0x6c, 0x26, 0xf1, 0xee, 0xa8, 0x4d, 0xc8, 0xaa, 0x16, 0x6f, 0x9f, 0xe1, 0x30, 0x04, 0xe4, 0x8e,
	0x73, 0xe2, 0x46, 0x13, 0xfb, 0xd5, 0xcd, 0x11, 0x07, 0x5b, 0xa4, 0x9e, 0x84, 0xd0, 0xdd, 0xea,
	0xfc, 0x8a, 0xf3, 0x7a, 0x7e, 0x6a, 0xf7, 0x6e, 0x59, 0xcf, 0xaa, 0x16, 0xff, 0x5d, 0xea, 0xd7,
	0xdf, 0x2e, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x25, 0x10, 0x42, 0x0a, 0x01, 0x00, 0x00,
}
