// Code generated by protoc-gen-go.
// source: type.proto
// DO NOT EDIT!

/*
Package pig is a generated protocol buffer package.

It is generated from these files:
	type.proto

It has these top-level messages:
*/
package pig

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TYPE int32

const (
	TYPE_UNKNOWN TYPE = 0
	TYPE_USER    TYPE = 1
	TYPE_ACTION  TYPE = 2
	TYPE_ARTICLE TYPE = 3
)

var TYPE_name = map[int32]string{
	0: "UNKNOWN",
	1: "USER",
	2: "ACTION",
	3: "ARTICLE",
}
var TYPE_value = map[string]int32{
	"UNKNOWN": 0,
	"USER":    1,
	"ACTION":  2,
	"ARTICLE": 3,
}

func (x TYPE) String() string {
	return proto.EnumName(TYPE_name, int32(x))
}
func (TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("pig.TYPE", TYPE_name, TYPE_value)
}

func init() { proto.RegisterFile("type.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xa9, 0x2c, 0x48,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0xc8, 0x4c, 0xd7, 0x32, 0xe3, 0x62, 0x09,
	0x89, 0x0c, 0x70, 0x15, 0xe2, 0xe6, 0x62, 0x0f, 0xf5, 0xf3, 0xf6, 0xf3, 0x0f, 0xf7, 0x13, 0x60,
	0x10, 0xe2, 0xe0, 0x62, 0x09, 0x0d, 0x76, 0x0d, 0x12, 0x60, 0x14, 0xe2, 0xe2, 0x62, 0x73, 0x74,
	0x0e, 0xf1, 0xf4, 0xf7, 0x13, 0x60, 0x02, 0x29, 0x71, 0x0c, 0x0a, 0xf1, 0x74, 0xf6, 0x71, 0x15,
	0x60, 0x4e, 0x62, 0x03, 0x9b, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x10, 0x52, 0x40,
	0x51, 0x00, 0x00, 0x00,
}
